#!/usr/bin/env python

import string, re, sys
from subprocess import Popen,PIPE


class Primer:
	## It appears the order of the parameters as they are entered into the file is important
	## That is why we break with "GENERIC_PARAMS_[*], with any parameters that 
	##  are changed during iterations 


	#PRIMER_TM_FORMULA=1 - refers to Santa Lucia JR (1998)
	#PRIMER_TM_FORMULA=0 - refers to Berlauer KJ (1986)
	#PRIMER_SALT_CORRECTIONS = 1 - refers to Santa Lucia JR (1998)
	#PRIMER_SALT_CORRECTIONS = 0 - refers to Schildkraut C (1965)
	#PRIMER_SALT_CORRECTIONS = 2 - refers to Owczarzy R (2008)


	def __init__(self,SEQUENCE_ID):
		self.SEQUENCE_ID="SEQUENCE_ID="+SEQUENCE_ID
		self.SEQUENCE_TEMPLATE="SEQUENCE_TEMPLATE="
		self.GENERIC_PARAMS_A="""PRIMER_FIRST_BASE_INDEX=1
PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT=1
PRIMER_THERMODYNAMIC_TEMPLATE_ALIGNMENT=0
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_INTERNAL_OLIGO=0
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_LIBERAL_BASE=1
PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS=0
"""
		self.GENERIC_PARAMS_Aa="""PRIMER_PICK_ANYWAY=0
PRIMER_EXPLAIN_FLAG=1
PRIMER_MASK_TEMPLATE=0
PRIMER_TASK=generic
PRIMER_MASK_FAILURE_RATE=0.1
PRIMER_MASK_5P_DIRECTION=1
PRIMER_MASK_3P_DIRECTION=0
PRIMER_MIN_QUALITY=0
PRIMER_MIN_END_QUALITY=0
PRIMER_QUALITY_RANGE_MIN=0
PRIMER_QUALITY_RANGE_MAX=100
"""

		self.GENERIC_PARAMS_B="""PRIMER_OPT_SIZE=25
PRIMER_MAX_SIZE=28
"""

		self.GENERIC_PARAMS_C="""PRIMER_OPT_TM=60
PRIMER_MAX_TM=64
PRIMER_PAIR_MAX_DIFF_TM=5.0
PRIMER_TM_FORMULA=1
PRIMER_PRODUCT_MIN_TM=-1000000.0
PRIMER_PRODUCT_OPT_TM=0.0
PRIMER_PRODUCT_MAX_TM=1000000.0
"""

		self.GENERIC_PARAMS_D="""PRIMER_NUM_RETURN=10
PRIMER_MAX_END_STABILITY=9.0
PRIMER_MAX_LIBRARY_MISPRIMING=12.00
PRIMER_PAIR_MAX_LIBRARY_MISPRIMING=20.00
PRIMER_MAX_SELF_ANY_TH=10
PRIMER_MAX_SELF_END_TH=10
PRIMER_PAIR_MAX_COMPL_ANY_TH=10
PRIMER_PAIR_MAX_COMPL_END_TH=10
PRIMER_MAX_HAIRPIN_TH=10
PRIMER_MAX_SELF_ANY=8.00
PRIMER_MAX_SELF_END=3.00
PRIMER_PAIR_MAX_COMPL_ANY=8.00
PRIMER_PAIR_MAX_COMPL_END=3.00
PRIMER_MAX_TEMPLATE_MISPRIMING_TH=40.00
PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH=70.00
PRIMER_MAX_TEMPLATE_MISPRIMING=12.00
PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING=24.00
PRIMER_MAX_NS_ACCEPTED=0
PRIMER_MAX_POLY_X=3
PRIMER_INSIDE_PENALTY=-1.0
PRIMER_OUTSIDE_PENALTY=0
PRIMER_GC_CLAMP=1
PRIMER_MAX_END_GC=5
PRIMER_MIN_LEFT_THREE_PRIME_DISTANCE=3
PRIMER_MIN_RIGHT_THREE_PRIME_DISTANCE=3
PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION=7
PRIMER_MIN_3_PRIME_OVERLAP_OF_JUNCTION=4
PRIMER_SALT_MONOVALENT=50.0
PRIMER_SALT_CORRECTIONS=1
PRIMER_SALT_DIVALENT=1.5
PRIMER_DNTP_CONC=0.6
PRIMER_DNA_CONC=50.0
PRIMER_SEQUENCING_SPACING=500
PRIMER_SEQUENCING_INTERVAL=250
PRIMER_SEQUENCING_LEAD=50
PRIMER_SEQUENCING_ACCURACY=20
PRIMER_WT_SIZE_LT=1.0
PRIMER_WT_SIZE_GT=1.0
PRIMER_WT_TM_LT=1.0
PRIMER_WT_TM_GT=1.0
PRIMER_WT_GC_PERCENT_LT=0.0
PRIMER_WT_GC_PERCENT_GT=0.0
PRIMER_WT_SELF_ANY_TH=0.0
PRIMER_WT_SELF_END_TH=0.0
PRIMER_WT_HAIRPIN_TH=0.0
PRIMER_WT_TEMPLATE_MISPRIMING_TH=0.0
PRIMER_WT_SELF_ANY=0.0
PRIMER_WT_SELF_END=0.0
PRIMER_WT_TEMPLATE_MISPRIMING=0.0
PRIMER_WT_NUM_NS=0.0
PRIMER_WT_LIBRARY_MISPRIMING=0.0
PRIMER_WT_SEQ_QUAL=0.0
PRIMER_WT_END_QUAL=0.0
PRIMER_WT_POS_PENALTY=0.0
PRIMER_WT_END_STABILITY=0.0
PRIMER_WT_MASK_FAILURE_RATE=0.0
PRIMER_PAIR_WT_PRODUCT_SIZE_LT=0.0
PRIMER_PAIR_WT_PRODUCT_SIZE_GT=0.0
PRIMER_PAIR_WT_PRODUCT_TM_LT=0.0
PRIMER_PAIR_WT_PRODUCT_TM_GT=0.0
PRIMER_PAIR_WT_COMPL_ANY_TH=0.0
PRIMER_PAIR_WT_COMPL_END_TH=0.0
PRIMER_PAIR_WT_TEMPLATE_MISPRIMING_TH=0.0
PRIMER_PAIR_WT_COMPL_ANY=0.0
PRIMER_PAIR_WT_COMPL_END=0.0
PRIMER_PAIR_WT_TEMPLATE_MISPRIMING=0.0
PRIMER_PAIR_WT_DIFF_TM=0.0
PRIMER_PAIR_WT_LIBRARY_MISPRIMING=0.0
PRIMER_PAIR_WT_PR_PENALTY=1.0
PRIMER_PAIR_WT_IO_PENALTY=0.0
PRIMER_INTERNAL_MIN_SIZE=18
PRIMER_INTERNAL_OPT_SIZE=20
PRIMER_INTERNAL_MAX_SIZE=27
PRIMER_INTERNAL_MIN_TM=57.0
PRIMER_INTERNAL_OPT_TM=60.0
PRIMER_INTERNAL_MAX_TM=63.0
PRIMER_INTERNAL_MIN_GC=20.0
PRIMER_INTERNAL_OPT_GC_PERCENT=50.0
PRIMER_INTERNAL_MAX_GC=80.0
PRIMER_INTERNAL_MAX_SELF_ANY_TH=47.00
PRIMER_INTERNAL_MAX_SELF_END_TH=47.00
PRIMER_INTERNAL_MAX_HAIRPIN_TH=47.00
PRIMER_INTERNAL_MAX_SELF_ANY=12.00
PRIMER_INTERNAL_MAX_SELF_END=12.00
PRIMER_INTERNAL_MIN_QUALITY=0
PRIMER_INTERNAL_MAX_NS_ACCEPTED=0
PRIMER_INTERNAL_MAX_POLY_X=5
PRIMER_INTERNAL_MAX_LIBRARY_MISHYB=12.00
PRIMER_INTERNAL_SALT_MONOVALENT=50.0
PRIMER_INTERNAL_DNA_CONC=50.0
PRIMER_INTERNAL_SALT_DIVALENT=1.5
PRIMER_INTERNAL_DNTP_CONC=0.0
PRIMER_INTERNAL_WT_SIZE_LT=1.0
PRIMER_INTERNAL_WT_SIZE_GT=1.0
PRIMER_INTERNAL_WT_TM_LT=1.0
PRIMER_INTERNAL_WT_TM_GT=1.0
PRIMER_INTERNAL_WT_GC_PERCENT_LT=0.0
PRIMER_INTERNAL_WT_GC_PERCENT_GT=0.0
PRIMER_INTERNAL_WT_SELF_ANY_TH=0.0
PRIMER_INTERNAL_WT_SELF_END_TH=0.0
PRIMER_INTERNAL_WT_HAIRPIN_TH=0.0
PRIMER_INTERNAL_WT_SELF_ANY=0.0
PRIMER_INTERNAL_WT_SELF_END=0.0
PRIMER_INTERNAL_WT_NUM_NS=0.0
PRIMER_INTERNAL_WT_LIBRARY_MISHYB=0.0
PRIMER_INTERNAL_WT_SEQ_QUAL=0.0
PRIMER_INTERNAL_WT_END_QUAL=0.0
"""
		self.ENDFILE="""=
"""
		self.PRIMER_PRODUCT_SIZE_RANGE="PRIMER_PRODUCT_SIZE_RANGE=175-300 301-500 501-750 751-1000 1001-1200\n"
		self.PRIMER_MIN_GC="PRIMER_MIN_GC=45\n"
		self.PRIMER_MAX_GC="PRIMER_MAX_GC=54\n"
		self.PRIMER_MIN_SIZE="PRIMER_MIN_SIZE=22\n"
		self.PRIMER_MIN_TM="PRIMER_MIN_TM=58.0\n"
		self.MASKING="PRIMER_LOWERCASE_MASKING=1\n"
		self.PRIMER_OPT_GC_PERCENT="PRIMER_OPT_GC_PERCENT=50.0\n"

	def updateParams(self,attemptNum):
		##Each attempt will be cumulative
		## (e.g. at attempt 2, PRIMER_MIN_GC =35 AND PRIMER_MAX_GC = 65
		if attemptNum == 1:
			self.PRIMER_MIN_GC="PRIMER_MIN_GC=35\n"
		elif attemptNum == 2:
			self.PRIMER_MAX_GC="PRIMER_MAX_GC=65\n"
		elif attemptNum == 3:
			self.PRIMER_MIN_TM="PRIMER_MIN_TM=55.0\n"
		elif attemptNum == 4:
			self.PRIMER_MIN_SIZE="PRIMER_MIN_SIZE=20\n"
		elif attemptNum == 5:
			##Now we're getting desperate, removing lower case
			## masking (PRIMER_LOWERCASE_MASKING) is a game changer
			## so we reset all params to standard first
			self.PRIMER_MIN_GC="PRIMER_MIN_GC=45\n"
			self.PRIMER_MAX_GC="PRIMER_MAX_GC=54\n"
			self.PRIMER_MIN_SIZE="PRIMER_MIN_SIZE=22\n"
			self.PRIMER_MIN_TM="PRIMER_MIN_TM=58.0\n"
			self.PRIMER_OPT_GC_PERCENT="PRIMER_OPT_GC_PERCENT=50.0\n"
			self.MASKING="PRIMER_LOWERCASE_MASKING=0\n"
		elif attemptNum == 6:
			self.PRIMER_MIN_GC="PRIMER_MIN_GC=35\n"
		elif attemptNum == 7:	
			self.PRIMER_MAX_GC="PRIMER_MAX_GC=65\n"
		elif attemptNum == 8:
			self.PRIMER_MIN_SIZE="PRIMER_MIN_SIZE=20\n"
